version: "3"
services:
  reader:
    build: ../read-only_reader_service/
    ports:
      - "30000:30000"
    command: ./read-only-service
    depends_on:
      - db
    environment:
      - DB_PASSWORD=031501

  db:
    image: postgres:latest
    volumes:
      - ./.database/data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=031501
      - POSTGRES_DB=main
    ports:
      - 5437:5432
  
  test:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=reader
      - POSTGRES_DB=reader
    ports:
      - 5436:5432
    volumes: 
      - ./.test-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/test_init.sql
